### ISSUE TITLE
Córreccion del TP 

### ISSUE THREAD

**Issue by achani2497** [donalavalle/Team-PdeP#1]
Buenas tardes chiques! Espero que anden bien. Les dejo la corrección del TP:

-  Cosas preliminares:
    - Está excelente que hayan definido las funciones `cambiar[AtributoDelAuto]` dado que sirven (en gran parte) para evitar repetir logica. Mi recomendación en este tipo de funciones es que siempre revisen bien el enunciado para ver si realmente las van a utilizar, porque puede ser que haya algún atributo de lo que modelen que no se tenga que modificar y estarían creando una función innecesaria. No es algo grave pero si se puede evitar, les recomiendo que lo hagan 😛
- Punto 1:
    - En el caso de las funciones como `estaEntreDJyNB` lo que mas les conviene es parametrizarlas. Por qué? Imaginen que se cambian las letras con las que se evaluan las patentes, y no solo eso, sino que se evaluan entre mas de dos pares de letras, lo cual los llevaría a tener que retocar su código, que en este tp no es la muerte de nadie pero en un laburo puede ser una tarea tediosa. Otro caso que se podría dar seria que haya un nuevo requerimiento en el cual puedan reutilizar la función, pero como ya la restringieron al requerimiento original, es probable que pisen el palito de la repetición de logica.
No está mal que hayan resuelto el punto así, pero la idea es que vayan adquiriendo el pensamiento de “y si cambian este requerimiento por…”, o sea, de que se imaginen distintos escenarios posibles para una función y traten de armar una solución única que englobe todos o por lo menos la mayoría de los escenarios.
    * Aplica la misma observación que antes para las funciones `patenteNueva` y `elUltimoEsCuatro`
* Punto 2:
    * En la funcion `primeraLlanta` aplica la misma observacion que para la funcion `estaEntreDJyNB` del punto 1.
* Punto 3: 
    * En casos como este, donde tienen varias funciones con la misma firma, pueden hacer `alfa, bravo, tango, zulú, lima : : Técnico`
* Punto 4:
    * En este punto si bien la solución hace lo que tiene que hacer, eligieron una forma algo rebuscada de hacerla. Ya que eligieron recorrer la lista recursivamente, podrían haber utilizado `even` y `odd` directamente.
* Punto 5:
    * Este punto está bien resuelto pero les voy a pedir que lo resuelvan utilizando `fold` 
* Punto 6: 
    * Item a:
        * Este está bien resuelto.
    * Item b:
        * En este punto en realidad tienen que devolver una lista con el costo de reparación de cada auto que necesite reparación, no el total. En el ejemplo se muestra un precio total a modo de verificación de la lista que se debería devolver, lo cual entiendo que los confundió, perdón por esa ambigüedad. 
* Punto 7:
    * Item a:
        * Me resultó curioso que hayan definido una función para testear esto pero en la consola la volvieron a definir 😆. Mas allá de esto, necesito que me fundamenten con la teoría que vimos en clase por qué se puede pedir el primero.
    * Item b:
        * Acá si bien la justificación es un poco mas clara que en el ítem anterior, tambien hace falta que me mencionen el concepto por el cual no se podría terminar de evaluar. La modificación que hicieron está bien pero tienen que tener en cuenta la corrección que les mencioné en el ítem b del punto 6.

En general me gustó bastante su TP, fueron sumamente prolijos y se hizo fácil de corregir. Tambien se nota que vienen entendiendo bastante los conceptos generales de la materia. 

### Les voy a pedir que modifiquen los siguientes puntos teniendo en cuenta las cosas que les marqué: 1, 2, 4, 5. Por otro lado, también quiero que corrijan las respuestas del punto 7 (tanto el ítem a como el ítem b)

Como siempre, si tienen alguna consulta sobre alguna de las correcciones me pueden hablar por discord 🙂
Saludos!

**Comment by Lautaro-L** [comment]
Ahí subimos las correcciones ale.
